### ISSUE TITLE
Training always results in NaN

### ISSUE THREAD

**Issue by lintangsutawika** [snipsco/ntm-lasagne#34] opened 2016-11-23 19:02 UTC
I've been trying to run the ```copy-task.py``` directly after installing and everytime it seems to result in ```NaN```
```
THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32,cnmem=0.2 PYTHONPATH=. python examples/copy-task.py
/home/lintangsutawika/anaconda2/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg/theano/configdefaults.py:1695: UserWarning: Theano does not recognise this flag: cnmem
  warnings.warn('Theano does not recognise this flag: {0}'.format(key))
Using gpu device 0: GeForce GTX 1060 6GB (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 5105)
/home/lintangsutawika/anaconda2/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
/home/lintangsutawika/anaconda2/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Batch #0: 0.686467
Batch #500: 0.341355
Batch #1000: 0.311876
Batch #1500: nan
Batch #2000: nan
Batch #2500: nan
Batch #3000: nan
```

What could be the problem? I once ran it on another computer a month ago and was working fine. Could it be a dependency problem?

**Comment by tristandeleu** [comment] 2016-11-24 10:32
By default there is no gradient clipping applied in this example. However, from my experience with the settings in these examples, `NaN` values may sometimes happen unfortunately because of an unlucky initialization. If you didn't experience any successful run at all, trying gradient clipping may be worth a try!

**Comment by frankjinhao** [comment] 2016-12-14 15:04
Hi, I have also experienced this before. After investigation, I identified the cause is in ntm.heads.py, specifically in HeadCollection's get_weights() method. Just before the last return statement, there is a "w /= T.sum(w, axis=2).dimshuffle(0, 1, 'x')", however T.sum(w, axis=2).dimshuffle(0, 1, 'x') sometimes equals to 0, getting INF here, thus leading to NAN in subsequent iterations. I have done a quick fix for this, which is adding  "w = w + 1e-6" before this statement to smoothen it out. Now it never trigger NAN for me. Hope this can address your issue. Thanks!

**Comment by opocaj92** [comment] 2018-07-13 10:58
Hi,
Don't know if the library is still developed or anyone is still using that, but maybe I figured out what causes the NaN error during the training. This error happens with the two default controllers (DenseController and RecurrentController), while the two I wrote don't suffer from this issue (LSTMController and GRUController). So I looked out for any difference in the code, and I found out that the original two are using lasagne.nonlinearities.rectify as the activation function, while mine use lasagne.nonlinearities.tanh.
Now, it is known that ReLU can suffer from the so-called "dying ReLU" problem, so I tried to switch to the Leaky ReLU activation (lasagne.nonlinearities.leaky_relu), but this still didn't solve the issue (don't know why, also tried with ELU). But, if I use the tanh istead everything just works fine.
So, probably an insight on what causes every ReLU-kind-of activation to result in a NaN error during training while the other functions work fine can solve definitively this issue.

**Comment by tristandeleu** [comment] 2018-07-13 13:32
That was my experience as well with NTM on a different code-base: ReLU, Leaky ReLU and ELU all were leading to NaNs fairly often, whereas tanh was a little more robust (still had some occasional NaNs though) on the copy task. However from my past experience with NTM Lasagne, I was not able to make the NTM with tanh converge on repeat copy and associative recall tasks (but in the cases where ReLU was not giving NaNs, NTM with ReLU was performing well on these tasks).

The choice of leaving ReLU as default was based on this, but maybe it would deserve an update!

**Comment by opocaj92** [comment] 2018-07-16 12:09
Ok, I've carried out some other experiments and the DenseController seems to result in the NaN error even with the tanh activation function (even if this happened a lot of iterations later), expecially with more than one head per type, so the problem is (at least not entirely) due to the controller's activation function.

**Closed** 2018-08-03 17:40 UTC
